# Sample config

bridge:
  # Domain part of the bridge, e.g. matrix.org
  domain: "localhost"
  # HomeServer URL
  homeserverUrl: "http://localhost:8008"
  # MX inbound domain. 
  # This is the domain to which inbound mails are sent by email users
  mxDomain: "localhost"
  # Mail submission port (587 is recommended)
  mailPort: 2525
  # The TCP port on which the appservice runs on.
  port: 8090
