# Sample config

bridge:
  # Domain part of the bridge, e.g. matrix.org
  domain: "localhost"
  # HomeServer URL
  homeserverUrl: "http://localhost:8008"
  # The TCP port on which the appservice runs on.
  port: 8090
  # MX inbound domain.
  # This is the domain to which inbound mails are sent by email users
  mxDomain: "localhost"
  # SMTP inbound port.
  mailPort: 2525
  # SMTP outbound port.
  outboundPort: 25
  # DKIM private key file location(eg: './dkim-private.pem'). Empty string for no DKIM signing
  dkimPrivateKeyLocation: ''
  # DKIM selector name. Leave empty for no DKIM
  dkimSelector: ''
