type: "object"
required: ["bridge"]
properties:
    bridge:
        type: "object"
        required: ["domain", "homeserverUrl", "mxDomain", "mailPort"]
        properties:
          domain:
            type: "string"
          homeserverUrl:
            type: "string"
          mxDomain:
            type: "string"
          mailPort:
            type: "number"
          port:
            type: "number"
          outboundPort:
            type: "number"
          smtpHost:
            type: "string"
          dkimPrivateKeyLocation:
            type: "string"
          dkimSelector:
            type: "string"

