"$schema": "http://json-schema.org/draft-04/schema#"
type: "object"
required: ["bridge", "email"]
properties:
  bridge:
    type: "object"
    required: ["domain", "homeserverUrl", "port"]
    properties:
      domain:
        type: "string"
      homeserverUrl:
        type: "string"
      port:
        type: "number"
  email:
    type: "object"
    required: ["mxDomain", "inboundPort", "outboundPort"]
    properties:
      mxDomain:
        type: "string"
      inboundPort:
        type: "number"
      outboundPort:
        type: "number"
      smtpHost:
        type: "string"
      dkim:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          dkimKey:
            type: "string"
          selector:
            type: "string"
      tls:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          tlsKey:
            type: "string"
          tlsCert:
            type: "string"
